import struct

PACKED_UINT8  = "B"
PACKED_UINT16 = "H"
PACKED_INT16  = "h"
PACKED_UINT32 = "I"
PACKED_UINT64 = "Q"

ESM_REPORT_MAGIC_NUM                = 0x45534D52
ESM_CONTROL_MAGIC_NUM               = 0x45534D43

ESM_MODULE_ID_CONTROL               = 0x00
ESM_MODULE_ID_DWELL_STATS_NARROW    = 0x02
ESM_MODULE_ID_DWELL_STATS_WIDE      = 0x03
ESM_MODULE_ID_PDW_NARROW            = 0x04
ESM_MODULE_ID_PDW_WIDE              = 0x05

ESM_CONTROL_MESSAGE_TYPE_ENABLE     = 0x00

ESM_REPORT_MESSAGE_TYPE_DWELL_STATS = 0x11
ESM_REPORT_MESSAGE_TYPE_PDW_PULSE   = 0x20
ESM_REPORT_MESSAGE_TYPE_PDW_SUMMARY = 0x21
ESM_REPORT_MESSAGE_TYPE_STATUS      = 0x30

ESM_NUM_CHANNELS_WIDE               = 8
ESM_NUM_CHANNELS_NARROW             = 64

TRANSFER_SIZE = 256

PACKED_ESM_REPORT_COMMON_HEADER = struct.Struct("<" + PACKED_UINT32 + PACKED_UINT32 + "xx" + PACKED_UINT8 + PACKED_UINT8)

PACKED_ESM_CONFIG_HEADER  = struct.Struct("<" + PACKED_UINT32 + PACKED_UINT32 + "xx" + PACKED_UINT8 + PACKED_UINT8 + "xxxx")
PACKED_ESM_CONFIG_CONTROL = struct.Struct("<" + PACKED_UINT32 + PACKED_UINT32 + "xx" + PACKED_UINT8 + PACKED_UINT8 + "xxxx" +
                                                PACKED_UINT8 + PACKED_UINT8 + PACKED_UINT8 + PACKED_UINT8 + "xxxx")
